"""Raster email derivatives of Header.astro/favicon.svg, using the site's font.
Run with fonttools/brotli available; PNG rendering uses project-local sharp.
"""
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
import subprocess
root=Path(__file__).resolve().parent.parent
font=TTFont(root/'public/fonts/IBMPlexMono-SemiBold.woff2')
glyphs=font.getGlyphSet(); cmap=font.getBestCmap(); units=font['head'].unitsPerEm

def paths(text,x,y,size):
    scale=size/units; result=[]
    for ch,color in text:
        name=cmap[ord(ch)]; pen=SVGPathPen(glyphs)
        glyphs[name].draw(TransformPen(pen,(scale,0,0,-scale,x,y)))
        result.append(f'<path fill="{color}" d="{pen.getCommands()}"/>')
        x+=font['hmtx'][name][0]*scale
    return ''.join(result)
word=paths([(ch,'#0ea5e9' if 11<=i<=12 else '#061532') for i,ch in enumerate('how-to-use-ai.com')],20,33,20)
logo=f'<svg xmlns="http://www.w3.org/2000/svg" width="260" height="52" viewBox="0 0 260 52"><title>how-to-use-ai.com</title><rect width="260" height="52" rx="26" fill="white"/>{word}<rect x="235" y="16" width="1" height="22" fill="#061532" opacity=".6"/></svg>'
advance=sum(font['hmtx'][cmap[ord(c)]][0] for c in 'ai')*28/units
icon=f'<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64"><title>ai</title><rect width="64" height="64" rx="14" fill="#061532"/>{paths([(c,"#0ea5e9") for c in "ai"],(64-advance)/2,42,28)}</svg>'
for name,svg in [('email-wordmark',logo),('email-favicon',icon)]:
    path=root/f'public/images/{name}.svg';path.write_text(svg)
    subprocess.run(['node','--input-type=module','-e',"import sharp from 'sharp'; await sharp(process.argv[1],{density:192}).png().toFile(process.argv[2]);",str(path),str(path.with_suffix('.png'))],cwd=root,check=True)

# MailerSend inline attachments avoid remote image requests from inbox clients.
import base64, json
attachments=[{'content':base64.b64encode((root/f'public/images/{name}.png').read_bytes()).decode(),'filename':name+'.png','disposition':'inline','id':name} for name in ['email-wordmark','email-favicon']]
(root/'src/lib/email/branding.ts').write_text('// Generated by scripts/generate-email-branding.py; do not edit base64 manually.\nexport const brandAttachments = '+json.dumps(attachments)+';\n')
