#!/usr/bin/env bash
#
# publish-books.sh
#
# Review-only PDF export of any book under ./docs that currently has
# drafted chapter content. Concatenates that book's chapters (in filename
# order, so chapter-01 ... chapter-14 then epilogue-*) into a single
# Markdown file and converts it to PDF with pandoc, for the author to
# proof-read a full draft outside the repo's Markdown source.
#
# This is a drafting/review convenience, not the series' final publishing
# pipeline (see docs/03-publishing/decisions/ADR-03-0001-manuscript-source-format.md,
# which leaves the production conversion pipeline to a later decision).
#
# Usage:
#   ./publish-books.sh              # publish every book with chapters
#   ./publish-books.sh 02-book-01   # publish only that book directory
#
# Output:
#   ./dist/<book-dir>.md   (intermediate combined manuscript)
#   ./dist/<book-dir>.pdf  (final PDF for review)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
OUT_DIR="$ROOT_DIR/dist"

if ! command -v pandoc >/dev/null 2>&1; then
  echo "Error: pandoc is required but not installed (brew install pandoc)." >&2
  exit 1
fi

PDF_ENGINE=""
for engine in xelatex lualatex wkhtmltopdf; do
  if command -v "$engine" >/dev/null 2>&1; then
    PDF_ENGINE="$engine"
    break
  fi
done

if [[ -z "$PDF_ENGINE" ]]; then
  echo "Error: no PDF engine found (need xelatex, lualatex, or wkhtmltopdf)." >&2
  echo "On macOS: brew install --cask basictex   (then restart your shell)" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Book directories to consider: either explicit argument(s), or every
# docs/*-book-*/ directory that has a chapters/ folder with .md files.
book_dirs=()
if [[ $# -gt 0 ]]; then
  for arg in "$@"; do
    book_dirs+=("$DOCS_DIR/$arg")
  done
else
  for dir in "$DOCS_DIR"/*-book-*/; do
    [[ -d "${dir}chapters" ]] && book_dirs+=("${dir%/}")
  done
fi

if [[ ${#book_dirs[@]} -eq 0 ]]; then
  echo "No book directories with chapter content found under $DOCS_DIR." >&2
  exit 1
fi

published_any=0

for book_dir in "${book_dirs[@]}"; do
  book_name="$(basename "$book_dir")"
  chapters_dir="$book_dir/chapters"

  if [[ ! -d "$chapters_dir" ]]; then
    echo "Skipping $book_name: no chapters/ directory." >&2
    continue
  fi

  # Filename order puts chapter-01 .. chapter-14 before epilogue-* (c < e),
  # and zero-padded numbers sort correctly within the chapter series.
  chapter_files=()
  while IFS= read -r f; do
    chapter_files+=("$f")
  done < <(find "$chapters_dir" -maxdepth 1 -name '*.md' | sort)

  if [[ ${#chapter_files[@]} -eq 0 ]]; then
    echo "Skipping $book_name: no drafted chapters yet." >&2
    continue
  fi

  echo "Publishing $book_name (${#chapter_files[@]} files)..."

  book_title="$(echo "$book_name" | sed -E 's/^[0-9]+-//; s/-/ /g')"
  combined_md="$OUT_DIR/$book_name.md"
  output_pdf="$OUT_DIR/$book_name.pdf"

  {
    echo "---"
    echo "title: \"$book_title (review draft)\""
    echo "date: \"$(date +%Y-%m-%d)\""
    echo "---"
    echo
    echo "> Review draft generated by publish-books.sh. Not a final publishing output."
    echo
    for f in "${chapter_files[@]}"; do
      cat "$f"
      echo
      echo '\newpage'
      echo
    done
  } > "$combined_md"

  # xelatex/lualatex hyphenate words at line breaks by default (e.g.
  # "impossible" -> "im-possible"); disable that for review PDFs, but only
  # if the hyphenat LaTeX package is actually installed (e.g. BasicTeX
  # installs often lack it), otherwise pandoc fails outright.
  no_hyphenate_args=()
  if [[ "$PDF_ENGINE" == "xelatex" || "$PDF_ENGINE" == "lualatex" ]] \
      && command -v kpsewhich >/dev/null 2>&1 \
      && kpsewhich hyphenat.sty >/dev/null 2>&1; then
    no_hyphenate_args=(-V header-includes='\usepackage[none]{hyphenat}')
  fi

  if ! pandoc "$combined_md" \
    -o "$output_pdf" \
    --pdf-engine="$PDF_ENGINE" \
    --toc \
    -V geometry:margin=1in \
    -V mainfont="Helvetica" \
    "${no_hyphenate_args[@]+"${no_hyphenate_args[@]}"}" 2>/dev/null; then
    # Retry without mainfont (Helvetica may not resolve for this engine).
    # Drop hyphenat handling here too: a failure above means it's not the
    # safe, always-available part of the command.
    pandoc "$combined_md" -o "$output_pdf" --pdf-engine="$PDF_ENGINE" --toc -V geometry:margin=1in
  fi

  echo "  -> $output_pdf"
  published_any=1
done

if [[ "$published_any" -eq 0 ]]; then
  echo "Nothing was published." >&2
  exit 1
fi

echo "Done. Review PDFs are in $OUT_DIR/"
